export const GET_ARTICLE_GROUPS_START =
  'ARTICLE_GROUPS/GET_ARTICLE_GROUPS_START'

export const GET_ARTICLE_GROUPS_SUCCEED =
  'ARTICLE_GROUPS/GET_ARTICLE_GROUPS_SUCCEED'

export const GET_ARTICLE_GROUPS_FAIL = 'ARTICLE_GROUPS/GET_ARTICLE_GROUPS_FAIL'
