require:
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Include

AllCops:
  DisplayStyleGuide: true
  Include:
    - 'db/*.schema'
  Exclude:
    - 'vendor/**/*'

Style/AsciiComments:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: braces_for_chaining

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericPredicate:
  AutoCorrect: true
  EnforcedStyle: comparison

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Metrics:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: true

Metrics/LineLength:
  Enabled: true
  Max: 120

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Performance/OpenStruct:
  Enabled: true
