require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'Gemfile'
    - 'r02/Rakefile'
    - 'r02/app/channels/application_cable/channel.rb'
    - 'r02/app/channels/application_cable/connection.rb'
    - 'r02/app/controllers/application_controller.rb'
    - 'r02/app/controllers/digiweb_controller.rb'
    - 'r02/app/controllers/placeorders/application_controller.rb'
    - 'r02/app/controllers/placeorders/home_controller.rb'
    - 'r02/app/jobs/application_job.rb'
    - 'r02/app/mailers/application_mailer.rb'
    - 'r02/app/models/application_record.rb'
    - 'r02/bin/bundle'
    - 'r02/bin/rails'
    - 'r02/bin/rake'
    - 'r02/bin/rspec'
    - 'r02/bin/setup'
    - 'r02/bin/spring'
    - 'r02/bin/update'
    - 'r02/bin/yarn'
    - 'r02/config.ru'
    - 'r02/config/application.rb'
    - 'r02/config/boot.rb'
    - 'r02/config/environment.rb'
    - 'r02/config/environments/production.rb'
    - 'r02/config/environments/test.rb'
    - 'r02/config/initializers/application_controller_renderer.rb'
    - 'r02/config/initializers/assets.rb'
    - 'r02/config/initializers/backtrace_silencers.rb'
    - 'r02/config/initializers/cookies_serializer.rb'
    - 'r02/config/initializers/filter_parameter_logging.rb'
    - 'r02/config/initializers/inflections.rb'
    - 'r02/config/initializers/mime_types.rb'
    - 'r02/config/initializers/new_framework_defaults_5_1.rb'
    - 'r02/config/initializers/rswag-api.rb'
    - 'r02/config/initializers/rswag-ui.rb'
    - 'r02/config/initializers/wrap_parameters.rb'
    - 'r02/config/puma.rb'
    - 'r02/config/spring.rb'
    - 'r02/spec/rails_helper.rb'
    - 'r02/spec/spec_helper.rb'
    - 'r02/spec/swagger_helper.rb'

RSpec/ContextWording:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
