require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'Gemfile'
    - 'r01/Gemfile'
    - 'r01/Rakefile'
    - 'r01/app/channels/application_cable/channel.rb'
    - 'r01/app/channels/application_cable/connection.rb'
    - 'r01/app/controllers/api/v1/presigned_urls_controller.rb'
    - 'r01/app/controllers/api/v1/user_avatars_controller.rb'
    - 'r01/app/controllers/application_controller.rb'
    - 'r01/app/controllers/posts_controller.rb'
    - 'r01/app/controllers/users_controller.rb'
    - 'r01/app/helpers/application_helper.rb'
    - 'r01/app/helpers/users_helper.rb'
    - 'r01/app/jobs/application_job.rb'
    - 'r01/app/mailers/application_mailer.rb'
    - 'r01/app/models/application_record.rb'
    - 'r01/app/models/post.rb'
    - 'r01/app/models/user.rb'
    - 'r01/app/models/user_avatar.rb'
    - 'r01/app/uploaders/avatar_uploader.rb'
    - 'r01/app/views/users/_user.json.jbuilder'
    - 'r01/app/views/users/index.json.jbuilder'
    - 'r01/app/views/users/show.json.jbuilder'
    - 'r01/bin/bundle'
    - 'r01/bin/importmap'
    - 'r01/bin/rails'
    - 'r01/bin/rake'
    - 'r01/bin/setup'
    - 'r01/config.ru'
    - 'r01/config/application.rb'
    - 'r01/config/boot.rb'
    - 'r01/config/environment.rb'
    - 'r01/config/environments/development.rb'
    - 'r01/config/environments/production.rb'
    - 'r01/config/environments/test.rb'
    - 'r01/config/importmap.rb'
    - 'r01/config/initializers/assets.rb'
    - 'r01/config/initializers/carrierwave.rb'
    - 'r01/config/initializers/config.rb'
    - 'r01/config/initializers/content_security_policy.rb'
    - 'r01/config/initializers/filter_parameter_logging.rb'
    - 'r01/config/initializers/inflections.rb'
    - 'r01/config/initializers/permissions_policy.rb'
    - 'r01/config/puma.rb'
    - 'r01/config/routes.rb'
    - 'r01/db/migrate/20230909050925_create_users.rb'
    - 'r01/db/migrate/20230909052102_add_avatar_to_users.rb'
    - 'r01/db/migrate/20231112114609_create_user_avatars.rb'
    - 'r01/db/migrate/20231112123542_remove_avatar_from_users.rb'
    - 'r01/db/migrate/20231123083046_create_posts.rb'
    - 'r01/db/schema.rb'
    - 'r01/db/seeds.rb'
    - 'r01/spec/factories/posts.rb'
    - 'r01/spec/factories/users.rb'
    - 'r01/spec/models/post_spec.rb'
    - 'r01/spec/models/user_avatar_spec.rb'
    - 'r01/spec/rails_helper.rb'
    - 'r01/spec/requests/api/v1/presigned_urls_spec.rb'
    - 'r01/spec/requests/api/v1/user_avatars_spec.rb'
    - 'r01/spec/requests/posts_spec.rb'
    - 'r01/spec/requests/users_spec.rb'
    - 'r01/spec/spec_helper.rb'
    - 'r01/test/application_system_test_case.rb'
    - 'r01/test/channels/application_cable/connection_test.rb'
    - 'r01/test/controllers/users_controller_test.rb'
    - 'r01/test/models/user_test.rb'
    - 'r01/test/system/users_test.rb'
    - 'r01/test/test_helper.rb'
    - 'r02/Rakefile'
    - 'r02/app/channels/application_cable/channel.rb'
    - 'r02/app/channels/application_cable/connection.rb'
    - 'r02/app/controllers/application_controller.rb'
    - 'r02/app/controllers/digiweb_controller.rb'
    - 'r02/app/controllers/placeorders/application_controller.rb'
    - 'r02/app/controllers/placeorders/home_controller.rb'
    - 'r02/app/jobs/application_job.rb'
    - 'r02/app/mailers/application_mailer.rb'
    - 'r02/app/models/application_record.rb'
    - 'r02/bin/bundle'
    - 'r02/bin/rails'
    - 'r02/bin/rake'
    - 'r02/bin/rspec'
    - 'r02/bin/setup'
    - 'r02/bin/spring'
    - 'r02/bin/update'
    - 'r02/bin/yarn'
    - 'r02/config.ru'
    - 'r02/config/application.rb'
    - 'r02/config/boot.rb'
    - 'r02/config/environment.rb'
    - 'r02/config/environments/production.rb'
    - 'r02/config/environments/test.rb'
    - 'r02/config/initializers/application_controller_renderer.rb'
    - 'r02/config/initializers/assets.rb'
    - 'r02/config/initializers/backtrace_silencers.rb'
    - 'r02/config/initializers/cookies_serializer.rb'
    - 'r02/config/initializers/filter_parameter_logging.rb'
    - 'r02/config/initializers/inflections.rb'
    - 'r02/config/initializers/mime_types.rb'
    - 'r02/config/initializers/new_framework_defaults_5_1.rb'
    - 'r02/config/initializers/rswag-api.rb'
    - 'r02/config/initializers/rswag-ui.rb'
    - 'r02/config/initializers/wrap_parameters.rb'
    - 'r02/config/puma.rb'
    - 'r02/config/spring.rb'
    - 'r02/spec/rails_helper.rb'
    - 'r02/spec/spec_helper.rb'
    - 'r02/spec/swagger_helper.rb'

RSpec/ContextWording:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
