version: '3.7'

services:
  app:
    image: ruby:2.7.4
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - ${PWD}/r02:/app
      - bundle:/usr/local/bundle
    command: bundle exec rails s -b 0.0.0.0

volumes:
  bundle: