export const GET_LIST_MENU_ITEMS_START =
  'LIST_MENU_ITEM/GET_LIST_MENU_ITEMS_START'

export const GET_LIST_MENU_ITEMS_SUCCEED =
  'LIST_MENU_ITEM/GET_LIST_MENU_ITEMS_SUCCEED'

export const GET_LIST_MENU_ITEMS_FAIL =
  'LIST_MENU_ITEM/GET_LIST_MENU_ITEMS_FAIL'
