default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: r02
  username: root
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { '' } %>
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { '0.0.0.0' } %>

development:
  <<: *default

test:
  <<: *default
  database: r02_test

production:
  <<: *default
  database: r02_production
  username: r02
  password: <%= ENV['R02_DATABASE_PASSWORD'] %>
