default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: r02
  username: root
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { 'password' } %>

development:
  <<: *default
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { '0.0.0.0' } %>

test:
  <<: *default
  host: <%= ENV.fetch("RAILS_TEST_DATABASE_HOST") { '0.0.0.0' } %>
  port: <%= ENV.fetch("RAILS_TEST_DATABASE_PORT") { '13306' } %>

production:
  <<: *default
  database: r02_production
  username: r02
  password: <%= ENV['R02_DATABASE_PASSWORD'] %>
